server:
  port: 8089

spring:
  application:
    name: pos-carts

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka
