openapi: "3.0.0"
info:
  version: 1.0.0
  title: Cart
  license:
    name: MIT
paths:
  /cart:
    get:
      summary: List all items of the cart
      operationId: listCart
      tags:
        - Cart
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        default:
          description: The request cannot be fulfilled due to bad syntax
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cart/add/{productId}:
    post:
      summary: Add an item to the cart
      operationId: addToCart
      tags:
        - Cart
      parameters:
        - name: productId
          in: path
          description: The ID of the product to add to the cart
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        default:
          description: The request cannot be fulfilled due to bad syntax
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /cart/checkout:
    post:
      summary: Checkout the cart
      operationId: checkoutCart
      tags:
        - Cart
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: integer
                format: int64
        default:
          description: The request cannot be fulfilled due to bad syntax
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: double
        image:
          type: string
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Item:
      type: object
      required:
        - product
        - quantity
      properties:
        product:
          $ref: "#/components/schemas/Product"
        quantity:
          type: integer
          format: int32
    Cart:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
    Order:
      type: object
      required:
        - cart
        - total
      properties:
        id:
          type: integer
          format: int64
        cart:
          $ref: "#/components/schemas/Cart"
        total:
          type: number
