openapi: "3.0.0"
info:
  version: 1.0.0
  title: Delivery
  license:
    name: MIT
paths:
  /delivery/byid/{id}:
    get:
      summary: get delivery by id
      operationId: getDeliveryById
      parameters:
        - name: id
          in: path
          description: Delivery ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Delivery found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: Invalid delivery
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /delivery/byorder/{orderId}:
    get:
      summary: find delivery by order id
      operationId: findDeliveryByOrderId
      parameters:
        - name: orderId
          in: path
          description: Order ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Delivery found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '400':
          description: Invalid delivery
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: double
        image:
          type: string
    Products:
      type: array
      items:
        $ref: "#/components/schemas/Product"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Item:
      type: object
      required:
        - product
        - quantity
      properties:
        product:
          $ref: "#/components/schemas/Product"
        quantity:
          type: integer
          format: int32
    Cart:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/Item"
    Order:
      type: object
      required:
        - cart
        - total
      properties:
        id:
          type: integer
          format: int64
        cart:
          $ref: "#/components/schemas/Cart"
        total:
          type: number
    Delivery:
      type: object
      required:
        - orderId
        - status
      properties:
        id:
          type: integer
          format: int64
        orderId:
          type: integer
          format: int64
        status:
          type: string
          enum:
            - CREATED
            - DELIVERED
            - CANCELED
